---
title: "COVID 19: AL, MS, LA"
runtime: shiny
output: 
  flexdashboard::flex_dashboard:
  orientation: rows
vertical_layout: fill
social: menu
theme: simplex
---

```{r setup, include=FALSE}
#knitr::opts_knit$set(root.dir = 'C:/Users/dmlong/Documents/GitHub/Covid19-Maps' )

library(flexdashboard)  
library(plotly) 
    
#Call create_map_chart_data to set up files for map
source("R/create_map_chart_data.R")
#Get AddTitle function
source("R/AddTitle.R")


states <- aggregate(char_count[, "STATEFP"], by = list(ID = char_count@data$STATEFP), 
                    FUN = unique, dissolve = T)


```


Column {data-width=650}
-----------------------------------------------------------------------

### Map 

```{r}

#Create Map output
output$map <- renderLeaflet({
map <-char_count %>%
  leaflet() %>%
  # add base map; this is blank to keep the plot from being too busy
  # minzoom = 7 keeps the user focussed on the southeastern US
  addProviderTiles("CartoDB.Positron", 
    options = tileOptions(minZoom = 6)) %>%
  # add layer one of counties: Case
  addPolygons(
    fillColor = ~ pal1(sum_cases),
    weight = 1,
    opacity = 0.3,
    color = "black",
    dashArray = "3",
    fillOpacity = 0.7,
   # popup = popupGraph(p1),   #Removed for Shiny app
    highlight = highlightOptions(
      weight = 2,
      color = "#666",
      dashArray = "",
      fillOpacity = 0.7,
      bringToFront = TRUE
    ),
    label = labels,
    labelOptions = labelOptions(textsize = "15px"),
    group = "Cases, total",
   layerId = ~NAME1
  )   %>%
  addPolygons(
    fillColor = ~ pal2(sum_deaths),
    weight = 1,
    opacity = 0.3,
    color = "black",
    dashArray = "3",
    fillOpacity = 0.7,
   # popup = popupGraph(p2),
    highlight = highlightOptions(
      weight = 2,
      color = "#666",
      dashArray = "",
      fillOpacity = 0.7,
      bringToFront = TRUE
    ),
    label = labels,
    labelOptions = labelOptions(textsize = "15px"),
    group = "Deaths, total" , layerId = ~NAME2
  ) %>%
  # add counties
  addPolygons(
    fillColor = ~ pal3(sum_cases_rate),
    weight = 1,
    opacity = 0.3,
    color = "black",
    dashArray = "3",
    fillOpacity = 0.7,
   # popup = popupGraph(p3),
    highlight = highlightOptions(
      weight = 2,
      color = "#666",
      dashArray = "",
      fillOpacity = 0.7,
      bringToFront = TRUE
    ),
    label = labels,
    labelOptions = labelOptions(textsize = "15px"),
    group = "Cases, rate" , layerId = ~NAME3
  )  %>%
  addPolygons(
    fillColor = ~ pal4(sum_deaths_rate),
    weight = 1,
    opacity = 0.3,
    color = "black",
    dashArray = "3",
    fillOpacity = 0.7,
   # popup = popupGraph(p4),
    highlight = highlightOptions(
      weight = 2,
      color = "#666",
      dashArray = "",
      fillOpacity = 0.7,
      bringToFront = TRUE
    ),
    label = labels,
    labelOptions = labelOptions(textsize = "15px"),
    group = "Deaths, rate" , layerId = ~NAME4
  ) %>% 
  addLayersControl(
    position = "topleft",
    baseGroups = c("Cases, total", "Deaths, total", 
      "Cases, rate", "Deaths, rate"),
    options = layersControlOptions(collapsed = FALSE)
  ) %>% 
  #Adds the darker lines for state borders
  addPolylines(data = states, color = "black", opacity = 1, weight = 3) %>%
  addLegend(
    pal = pal1,
    values = ~ sum_cases,
    opacity = 0.7,
    title = htmltools::HTML("Cases per <br> County"),
    position = "bottomright",
    group = "Cases, total"
  ) %>%
  addLegend(
    pal = pal2,
    values = ~ sum_deaths,
    opacity = 0.7,
    title = htmltools::HTML("Deaths per <br> County"),
    position = "bottomright",
    group = "Deaths, total"
  ) %>%
  addLegend(pal = pal3,
    values = ~sum_cases_rate,
    opacity = 0.7,
    title = htmltools::HTML("Case Rate <br> per 10,000"),
    position = "bottomleft",
    group="Cases, rate"
  ) %>% 
  addLegend(pal = pal4,
    values = ~sum_deaths_rate,
    opacity = 0.7,
    title = htmltools::HTML("Death rate <br> per 10,000"),
    position = "bottomleft",
    group="Deaths, rate"
  ) 
  
map
  
})  

#Get ID from layer clicks, must be unique for each layer

click_county <- eventReactive(input$map_shape_click, {
  x <- input$map_shape_click
  y <- x$id
  return(y)
})




county_data <- reactive({

  # Fetch data for the clicked county using click_county by removing the L* from the   # string which was added to create uniqueness
  return(
    covid_count[covid_count$NAME == str_remove(click_county()," L2| L3| L4"),] %>% select(NAME,pop,white,black,asian,sum_cases,sum_deaths,sum_cases_rate,sum_deaths_rate)
    )
})
leafletOutput('map')  


```

Column {data-width=350}
-----------------------------------------------------------------------

### Demographic Table {data-height=250}

```{r}


DT::renderDataTable({
  DT::datatable(county_data()[1:5], 
                options = list(bPaginate = FALSE,   scrollX = T, scrollY=T,
                                searching = F),
                class="compact cell-border",
      colnames = c("County", "Total Population","Whites","Blacks","Asians")
  )
})


```

### Covid Table {data-height=250}

```{r}


DT::renderDataTable({
  DT::datatable(county_data()[c(1,6:9)], 
                options = list( bPaginate = FALSE,   scrollX = T,scrollY=T,
                                searching = F),
                class="compact cell-border",
    colnames = c("County","Total Cases","Total Deaths",
                 "Case Rate","Death Rate")
  )

})


```

### Line Graph {data-height=500}

```{r}
# Here, we draw the diversity gradient with ggplotly


output$scatter <- renderPlotly({
  
  # Remove L* from layer ID to determine the correct county
  cc=str_remove(click_county()," L2| L3| L4")
  
  if(is.null(cc)){
    cc = "Jefferson County, Alabama"
  }
  
  #Find the row number for the clicked county to locate plot
  index = which(counties==cc)
  
  #If statements to pick appropriate plot based on current layer and ID
  if(str_detect(click_county(),"L2|L3|L4")==F){
    p1a = p1[[index]]
  }
  
  if(str_detect(click_county(),"L2")==T){
    p1a = p2[[index]]
  }
  
  if(str_detect(click_county(),"L3")==T){
    p1a = p3[[index]]
  }
  
  if(str_detect(click_county(),"L4")==T){
    p1a = p4[[index]]
  }
  
  g = ggplotly(p1a)
  
  build <- plotly_build(g)
  
  build
})
plotlyOutput('scatter')

```

